### ISSUE TITLE
Ability to update all nodes in a cluster

### ISSUE THREAD

**Issue by nirmal070125** [jnswso2/wso2-log-configurer#11]
We need the ability to update all the nodes in a cluster.

We can assume;
- username, password is same
- keystore and password is same

Only the hostname and port will be different.

**Comment by Kamidu** [comment]
###  **Proposed Solution**
Since we can assume, that the username, the password is the same and Keystore and password is the same, Simply we can enable the user to prove a single hostname or comma-separated set of hostnames when it comes to a cluster. 

@nirmal070125  Please let me know if this approach caters to your use case or do you prefer any other approach to handle this use case?
